apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: platform-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: platform-api
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: platform-api
    spec:
      volumes:
      - name: appsettings-volume
        configMap:
          name: appsettings.json
      - name: secrets-volume
        secret:
          secretName: appsecrets.json
      containers:
      - name: platform-api
        image: givt/platform-api:development
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: appsettings-volume
            mountPath: /app/config/appsettings.json
            subPath: appsettings.json
          - name: secrets-volume
            mountPath: /app/config/appsecrets.json
            subPath: appsecrets.json

