// <auto-generated />
using System;
using Givt.Persistance.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Givt.Persistance.Migrations
{
    [DbContext(typeof(GivtDbContext))]
    partial class GivtDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Givt.Domain.Entities.AppVersion", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<int>("BuildNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OperatingSystem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AppVersion");
                });

            modelBuilder.Entity("Givt.Domain.Entities.Authorisation", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("DonorOwnerId")
                        .HasColumnType("BINARY(16)");

                    b.Property<byte[]>("RecipientOwnerId")
                        .HasColumnType("BINARY(16)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserEmailNormalised")
                        .HasColumnType("varchar(200)");

                    b.HasKey("UserId", "ResourceId");

                    b.HasIndex("DonorOwnerId");

                    b.HasIndex("RecipientOwnerId");

                    b.HasIndex("UserEmailNormalised");

                    b.ToTable("Authorisations");
                });

            modelBuilder.Entity("Givt.Domain.Entities.Campaign", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<string>("Amounts")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("DefaultFeeId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Namespace")
                        .HasMaxLength(33)
                        .HasColumnType("varchar(33)");

                    b.Property<byte[]>("OwnerId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<byte[]>("PayOutMethodId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultFeeId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PayOutMethodId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Givt.Domain.Entities.CampaignTexts", b =>
                {
                    b.Property<byte[]>("CampaignId")
                        .HasColumnType("BINARY(16)");

                    b.Property<string>("LanguageId")
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<string>("Goal")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("ThankYou")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("Title")
                        .HasMaxLength(175)
                        .HasColumnType("varchar(175)");

                    b.HasKey("CampaignId", "LanguageId");

                    b.ToTable("CampaignTexts");
                });

            modelBuilder.Entity("Givt.Domain.Entities.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<byte[]>("GivtOfficeId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<ulong?>("PaymentMethods")
                        .HasColumnType("BIGINT UNSIGNED");

                    b.HasKey("Code");

                    b.HasIndex("GivtOfficeId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Givt.Domain.Entities.Donation", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<byte[]>("CampaignId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<DateTime>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("DonationDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("DonorId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<string>("Fingerprint")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Last4")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<byte[]>("MediumId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("PayinId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<byte[]>("RecipientId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("DonorId");

                    b.HasIndex("MediumId");

                    b.HasIndex("PayinId");

                    b.HasIndex("RecipientId");

                    b.HasIndex("TransactionReference");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("Givt.Domain.Entities.Donor", b =>
                {
                    b.Property<byte[]>("OwnerId")
                        .HasColumnType("BINARY(16)");

                    b.Property<string>("Language")
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<byte[]>("PrimaryPayInMethodId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("OwnerId");

                    b.HasIndex("PrimaryPayInMethodId");

                    b.ToTable("Donors");
                });

            modelBuilder.Entity("Givt.Domain.Entities.Fee", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fees");
                });

            modelBuilder.Entity("Givt.Domain.Entities.FeeAgreement", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<byte[]>("CampaignId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("FeeId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<int?>("MinVolumeAmount")
                        .HasColumnType("int");

                    b.Property<int?>("MinVolumeCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("RecipientId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("FeeId");

                    b.HasIndex("RecipientId");

                    b.ToTable("FeeAgreements");
                });

            modelBuilder.Entity("Givt.Domain.Entities.LegalEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ConcurrencyToken")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CountryId")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(175)
                        .HasColumnType("varchar(175)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(175)
                        .HasColumnType("varchar(175)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Preposition")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(175)
                        .HasColumnType("varchar(175)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("LegalEntities");
                });

            modelBuilder.Entity("Givt.Domain.Entities.Medium", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<byte[]>("CampaignId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<string>("MediumId")
                        .HasMaxLength(33)
                        .HasColumnType("varchar(33)");

                    b.Property<byte[]>("OwnerId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Mediums");

                    b.HasDiscriminator<int>("Class").HasValue(1);
                });

            modelBuilder.Entity("Givt.Domain.Entities.PayIn", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<byte[]>("DonorOwnerId")
                        .HasColumnType("BINARY(16)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExecutedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("PayInMethodId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<DateTime?>("PaymentProviderExecutionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TotalPaid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonorOwnerId");

                    b.HasIndex("PayInMethodId");

                    b.ToTable("PayIns");
                });

            modelBuilder.Entity("Givt.Domain.Entities.PayInMethod", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<byte[]>("OwnerId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<string>("PSP_Identification")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PSP_Owner")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("PayInMethod");

                    b.HasDiscriminator<int>("Class").HasValue(0);
                });

            modelBuilder.Entity("Givt.Domain.Entities.PayOut", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<byte[]>("CampaignId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExecutedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("GivtServiceFee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("GivtServiceFeeTaxes")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MandateCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("MandateCostCount")
                        .HasColumnType("int");

                    b.Property<decimal>("MandateTaxes")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PaymentCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PaymentCostTaxes")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("PaymentProviderExecutionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentProviderId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("RTransactionAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("RTransactionT1Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("RTransactionT1Count")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("RTransactionT2Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("RTransactionT2Count")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("RTransactionTaxes")
                        .HasColumnType("decimal(65,30)");

                    b.Property<byte[]>("RecipientOwnerId")
                        .HasColumnType("BINARY(16)");

                    b.Property<decimal>("TotalPaid")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TransactionCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TransactionCount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TransactionTaxes")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("RecipientOwnerId");

                    b.ToTable("PayOuts");
                });

            modelBuilder.Entity("Givt.Domain.Entities.PayOutMethod", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<string>("PSP_Identification")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PSP_Owner")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("RecipientId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.ToTable("PayOutMethod");
                });

            modelBuilder.Entity("Givt.Domain.Entities.Recipient", b =>
                {
                    b.Property<byte[]>("OwnerId")
                        .HasColumnType("BINARY(16)");

                    b.Property<byte[]>("DefaultCampaignId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(175)
                        .HasColumnType("varchar(175)");

                    b.Property<string>("LogoImageLink")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<byte[]>("PrimaryPayOutMethodId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.HasKey("OwnerId");

                    b.HasIndex("DefaultCampaignId");

                    b.HasIndex("PrimaryPayOutMethodId");

                    b.ToTable("Recipients");
                });

            modelBuilder.Entity("Givt.Domain.Entities.Timeslot", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<byte[]>("CampaignId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("MediumId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<byte[]>("OwnerId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("MediumId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Timeslots");
                });

            modelBuilder.Entity("Givt.Domain.Entities.User", b =>
                {
                    b.Property<string>("EmailNormalised")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OS")
                        .HasColumnType("int");

                    b.HasKey("EmailNormalised");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Givt.Domain.Entities.CreditCard", b =>
                {
                    b.HasBaseType("Givt.Domain.Entities.PayInMethod");

                    b.Property<string>("Fingerprint")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Last4")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Givt.Domain.Entities.Location", b =>
                {
                    b.HasBaseType("Givt.Domain.Entities.Medium");

                    b.Property<float>("Lat")
                        .HasColumnType("float");

                    b.Property<float>("Lon")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Radius")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Givt.Domain.Entities.Authorisation", b =>
                {
                    b.HasOne("Givt.Domain.Entities.Donor", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorOwnerId");

                    b.HasOne("Givt.Domain.Entities.Recipient", "Recipient")
                        .WithMany("Members")
                        .HasForeignKey("RecipientOwnerId");

                    b.HasOne("Givt.Domain.Entities.User", "User")
                        .WithMany("Authorisations")
                        .HasForeignKey("UserEmailNormalised");

                    b.Navigation("Donor");

                    b.Navigation("Recipient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Givt.Domain.Entities.Campaign", b =>
                {
                    b.HasOne("Givt.Domain.Entities.Fee", "DefaultFee")
                        .WithMany()
                        .HasForeignKey("DefaultFeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Givt.Domain.Entities.Recipient", "Owner")
                        .WithMany("Campaigns")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Givt.Domain.Entities.PayOutMethod", "PayOutMethod")
                        .WithMany()
                        .HasForeignKey("PayOutMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefaultFee");

                    b.Navigation("Owner");

                    b.Navigation("PayOutMethod");
                });

            modelBuilder.Entity("Givt.Domain.Entities.CampaignTexts", b =>
                {
                    b.HasOne("Givt.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Texts")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Givt.Domain.Entities.Country", b =>
                {
                    b.HasOne("Givt.Domain.Entities.LegalEntity", "GivtOffice")
                        .WithMany()
                        .HasForeignKey("GivtOfficeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GivtOffice");
                });

            modelBuilder.Entity("Givt.Domain.Entities.Donation", b =>
                {
                    b.HasOne("Givt.Domain.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Givt.Domain.Entities.Donor", "Donor")
                        .WithMany("Donations")
                        .HasForeignKey("DonorId");

                    b.HasOne("Givt.Domain.Entities.Medium", "Medium")
                        .WithMany()
                        .HasForeignKey("MediumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Givt.Domain.Entities.PayIn", "Payin")
                        .WithMany("Donations")
                        .HasForeignKey("PayinId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Givt.Domain.Entities.Recipient", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Donor");

                    b.Navigation("Medium");

                    b.Navigation("Payin");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("Givt.Domain.Entities.Donor", b =>
                {
                    b.HasOne("Givt.Domain.Entities.LegalEntity", "Owner")
                        .WithOne()
                        .HasForeignKey("Givt.Domain.Entities.Donor", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Givt.Domain.Entities.PayInMethod", "PrimaryPayInMethod")
                        .WithMany()
                        .HasForeignKey("PrimaryPayInMethodId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Owner");

                    b.Navigation("PrimaryPayInMethod");
                });

            modelBuilder.Entity("Givt.Domain.Entities.FeeAgreement", b =>
                {
                    b.HasOne("Givt.Domain.Entities.Campaign", "Campaign")
                        .WithMany("FeeAgreements")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Givt.Domain.Entities.Fee", "Fee")
                        .WithMany()
                        .HasForeignKey("FeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Givt.Domain.Entities.Recipient", "Recipient")
                        .WithMany("FeeAgreements")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Fee");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("Givt.Domain.Entities.LegalEntity", b =>
                {
                    b.HasOne("Givt.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Givt.Domain.Entities.Medium", b =>
                {
                    b.HasOne("Givt.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Mediums")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Givt.Domain.Entities.Recipient", "Owner")
                        .WithMany("Mediums")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Givt.Domain.Entities.PayIn", b =>
                {
                    b.HasOne("Givt.Domain.Entities.Donor", null)
                        .WithMany("PayIns")
                        .HasForeignKey("DonorOwnerId");

                    b.HasOne("Givt.Domain.Entities.PayInMethod", "PayInMethod")
                        .WithMany()
                        .HasForeignKey("PayInMethodId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PayInMethod");
                });

            modelBuilder.Entity("Givt.Domain.Entities.PayInMethod", b =>
                {
                    b.HasOne("Givt.Domain.Entities.Donor", "Owner")
                        .WithMany("PayInMethods")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Givt.Domain.Entities.PayOut", b =>
                {
                    b.HasOne("Givt.Domain.Entities.Campaign", "Campaign")
                        .WithMany("PayOuts")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Givt.Domain.Entities.Recipient", null)
                        .WithMany("PayOuts")
                        .HasForeignKey("RecipientOwnerId");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Givt.Domain.Entities.PayOutMethod", b =>
                {
                    b.HasOne("Givt.Domain.Entities.Recipient", "Recipient")
                        .WithMany("PayOutMethods")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("Givt.Domain.Entities.Recipient", b =>
                {
                    b.HasOne("Givt.Domain.Entities.Campaign", "DefaultCampaign")
                        .WithMany()
                        .HasForeignKey("DefaultCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Givt.Domain.Entities.LegalEntity", "Owner")
                        .WithOne()
                        .HasForeignKey("Givt.Domain.Entities.Recipient", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Givt.Domain.Entities.PayOutMethod", "PrimaryPayOutMethod")
                        .WithMany()
                        .HasForeignKey("PrimaryPayOutMethodId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DefaultCampaign");

                    b.Navigation("Owner");

                    b.Navigation("PrimaryPayOutMethod");
                });

            modelBuilder.Entity("Givt.Domain.Entities.Timeslot", b =>
                {
                    b.HasOne("Givt.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Timeslots")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Givt.Domain.Entities.Medium", "Medium")
                        .WithMany("Timeslots")
                        .HasForeignKey("MediumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Givt.Domain.Entities.Recipient", "Owner")
                        .WithMany("Timeslots")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Medium");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Givt.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("FeeAgreements");

                    b.Navigation("Mediums");

                    b.Navigation("PayOuts");

                    b.Navigation("Texts");

                    b.Navigation("Timeslots");
                });

            modelBuilder.Entity("Givt.Domain.Entities.Donor", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("PayInMethods");

                    b.Navigation("PayIns");
                });

            modelBuilder.Entity("Givt.Domain.Entities.Medium", b =>
                {
                    b.Navigation("Timeslots");
                });

            modelBuilder.Entity("Givt.Domain.Entities.PayIn", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("Givt.Domain.Entities.Recipient", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("FeeAgreements");

                    b.Navigation("Mediums");

                    b.Navigation("Members");

                    b.Navigation("PayOutMethods");

                    b.Navigation("PayOuts");

                    b.Navigation("Timeslots");
                });

            modelBuilder.Entity("Givt.Domain.Entities.User", b =>
                {
                    b.Navigation("Authorisations");
                });
#pragma warning restore 612, 618
        }
    }
}
