name: Givt Platform workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request
  push:
    branches: [ main, pre-main ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet v6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Development --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal